### ISSUE TITLE
bug: Node version parameter is incorrectly referenced

### ISSUE THREAD

**Issue by cubabit** [DerYeger/yarn-setup-action#45]
### Affected Packages

- [ ] @yeger/eslint-config
- [ ] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

The node-version parameter is not correctly references when passed to `setup-node` action.

i have created a PR https://github.com/DerYeger/yarn-setup-action/pull/44

### Reproduction

Use the node-version parameter when calling the action

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thanks for the issue report and PR!
